### ISSUE TITLE
current electricity not showed

### ISSUE THREAD

**Issue by JoeryMens** [koktaildotcom/com.p1.smartmeter#30]
I use DSMR Reader version 4.9; added the script https://github.com/koktaildotcom/com.p1.smartmeter-dsmr.reader
and installed this app on the homey. 
Now this app shows me the total energy consumption, the low&normal-tariff energy consumption, the low&normal-tariff energy returned and the gas statistics. 

However the 'current' electricity consumption/returned only show "-" while that are the most interesting values to use.

**Comment by koktaildotcom** [comment]
Have you tried updating node-dsmr?

**Comment by jilleb** [comment]
Same issue here. Yes, node-dsmr is up to date. It's sending data, but for some reason the current consumption is being ignored:
```{ power:
   { equipmentId: '***************',
     totalConsumed1: ****.973,
     totalConsumed2: ****.046,
     totalProduced1: 0,
     totalProduced2: 0,
     activeTariff: 2,
     actualConsumed: 0.457,
     actualProduced: 0,
     failures: 2,
     failuresLong: 0,
     failureLog: [],
     voltageSagsL1: 2,
     voltageSwellsL1: 0,
     instantaneousVoltageL1: 230,
     instantaneousCurrentL1: 2,
     instantaneousConsumedElectricityL1: 0.457,
     instantaneousProducedElectricityL1: 0 },
  gas:
   { equipmentId: '***************',
     timestamp: 1610703600,
     totalConsumed: ****.938,
     reportedPeriod: 5 },
  meterModel: '***************',
  dsmrVersion: 5,
  timestamp: 1610703853 }```

**Comment by koktaildotcom** [comment]
The app is using electricity.received.tariff1.reading and electricity.delivered.tariff1.reading to calcuate the 'current' electricity consumption/returned.

**Comment by koktaildotcom** [comment]
Fixed in 4.0.2.

**Comment by tjaadvd** [comment]
I am still experiencing this problem. Current usage is not showing data. 
<img width="422" alt="Schermafbeelding 2021-03-21 om 16 49 37" src="https://user-images.githubusercontent.com/171732/111911340-77bae880-8a65-11eb-8c15-4133e7b9ee0d.png">

**Comment by tjaadvd** [comment]
Also when I run 'docker exec -ti pi_dsmr_1 bash -c "./post-deploy.sh"' it gives me the error:
` --- Checking whether VirtualEnv is activated.
     [i] ----- Activating 'dsmrreader' VirtualEnv...
./post-deploy.sh: line 10: /root/.virtualenvs/dsmrreader/bin/activate: No such file or directory
     [!] FAILED to switch to 'dsmrreader' VirtualEnv (is it installed?)`

**Comment by lukevredeveld** [comment]
> I am still experiencing this problem. Current usage is not showing data.
> I've installed the plugin to DSMR Reader v4 in docker.
> <img alt="Schermafbeelding 2021-03-21 om 16 49 37" width="422" src="https://user-images.githubusercontent.com/171732/111911340-77bae880-8a65-11eb-8c15-4133e7b9ee0d.png">

I also have this problem... is there a solution for this? Because I don't really understand why this issue was closed when the problem still persists. I have the latest homey P1 app (4.0.3) but still no live-energy reports :-(

**Comment by Itsmmai** [comment]
same here. why is it closed when it is still not working ?
